name: pr_add_comment

on:
  pull_request_review_comment:
    types:
      - created

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment
      run: |
        echo "PR Comment 1" >> comments
        echo "PR Comment 2" >> comments
        echo "PR Comment 3" >> comments
        sed -i -z 's/\n/\\n/g' comments

    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             ${URL}
