name: pr_add_commit

on:
  pull_request:
    types:
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: |
        echo ${GITHUB_REF}
        echo running on branch ${GITHUB_REF##*/}
    - name: Create comment
      run: |
        git fetch --no-tags --depth=1 origin
        echo ${GITHUB_SHA}
        echo `git name-rev --refs ${GITHUB_SHA}`
        echo `git log`
        echo ${{ github.event.pull_request.head.sha }}
        echo `git name-rev --refs ${{ github.event.pull_request.head.sha }}`
        echo "PR add commit" >> comments
        echo "PR Comment 2" >> comments
        echo "PR Comment 3" >> comments
        sed -i -z 's/\n/\\n/g' comments

    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             ${URL}
