name: pr_add_comment

on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment
      if: github.event.issue.pull_request
      run: |
        echo "pr_add_comment" >> comments
        echo "PR Comment 1" >> comments
        echo "PR Comment 2" >> comments
        echo "PR Comment 3" >> comments
        sed -i -z 's/\n/\\n/g' comments

    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_PAYLOAD: ${{ toJson(github.event.issue) }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      if: github.event.issue.pull_request
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}
