name: pr_opened

on:
  pull_request:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create comment
      run: |
        echo "PR Opened" >> comments
        echo "branch name : ${git symbolic-ref --short HEAD}" >> comments
        sed -i -z 's/\n/\\n/g' comments

    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             ${URL}
