name: pr_opened

on:
  pull_request:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create comment
      env:
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        git fetch --no-tags --depth=1 origin
        HASH_AND_BRANCH=`git name-rev ${PR_HEAD_SHA}`
        BRANCH=`echo "${HASH_AND_BRANCH##*remotes/origin/}"`
        echo "PR Opened" >> comments
        echo "Branch name: ${BRANCH}" >> comments
        sed -i -z 's/\n/\\n/g' comments

    - name: Post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             ${URL}
